# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

minimal_mistakes_skin    : default  # "air", "aqua", "contrast", "dark", "dirt", "neon", "mint", "plum", "sunrise"

# Site Settings
locale                   : "vi-VN"
# Thêm logo đúng size vào đúng chỗ sẽ hiển thị phía trước tiêu đề trang web
# logo                     : "/assets/images/main/Logo-Thanh88x88.png" # ẩn logo, vì nhiều hình quá trông có vẻ rối
title                    : "Blog của Thành"
subtitle                 : # site tagline that appears below site title in masthead
description              : >- # this means to ignore newlines until "baseurl:"
  Đây là trang blog cá nhân của Thành, vừa là nơi chia sẻ, vừa là nơi ghi chú
  lại những kinh nghiệm cá nhân.

email: thanhag@gmail.com

twitter_username: rambothanh
github_username: rambothanh

search: true




# Build settings
markdown: kramdown
remote_theme: mmistakes/minimal-mistakes
# Outputting
permalink: /:categories/:title/
paginate: 5 # amount of posts to show
paginate_path: /page:num/
timezone: # https://en.wikipedia.org/wiki/List_of_tz_database_time_zones

include:
  - _pages

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# Plugins (previously gems:)
plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-feed
  - jemoji
  - jekyll-include-cache
  #- jekyll-archives  # Host trên Github nên không dùng được 

# Site Author
author:
  name          : "Thành"
  avatar        : /assets/images/main/thanh-avarta-dumaudep-fromSVG.png # ảnh trắng đen chuyển từ SVG cho nhẹ
                # /assets/images/main/thanh-avarta-dumaudep-fromSVG.png # ảnh trắng đen chuyển từ SVG cho nhẹ
                # /assets/images/main/Thanh-Avarta.png # Ảnh đủ màu  
                #"/assets/images/avarta-thanh.jpg"
                # /assets/images/main/thanh-avarta-dumaudep-vintage.png # ẢNH HIỆU ỨNG VINTAGE
  bio           : "Là một gã ít nói nhàm chán, chuyên về tài chính, thích mày mò công nghệ. Xem thêm tiểu sử của tôi qua facebook"
  location      : "An Giang, Việt Nam"
  links:
    - label: "Trang web"
      icon: "fas fa-fw fa-link"
      url: "https://sofsog.com"
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook"
      url: "https://facebook.com/rambothanh"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/rambothanh"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/rambothanh"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/rambothanh"
    - label: "Email"
      icon: "fas fa-fw fa-envelope-square"
      url: "mailto:rambothanh1985@gmail.com"  

footer:
  links:
    - label: "Facebook"
      icon: "fab fa-fw fa-facebook"
      url: "https://facebook.com/rambothanh"
    - label: "Twitter"
      icon: "fab fa-fw fa-twitter-square"
      url: "https://twitter.com/rambothanh"
    - label: "GitHub"
      icon: "fab fa-fw fa-github"
      url: "https://github.com/rambothanh"
    - label: "Instagram"
      icon: "fab fa-fw fa-instagram"
      url: "https://instagram.com/rambothanh"

teaser: /assets/images/500x300.png

defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values:
      # show_date: true # để hiển thị ngày tạo bài đăng, có thể add vào từng bài đăng
      layout: single
      author_profile: true
      read_time: true # Bật đoạn thời gian đọc ước tính
      comments: true
      share: true
      related: true
  # _pages
  - scope:
      path: "_pages"
      type: pages
    values:
      layout: single
      author_profile: true


# Cấu hình jekyll-archives # Host trên Github nên không dùng được 
# category_archive:
#   type: jekyll-archives
#   path: /
# tag_archive:
#   type: jekyll-archives
#   path: /
# # https://github.com/jekyll/jekyll-archives
# jekyll-archives:
#   enabled:
#     - categories
#     - tags
#   layouts:
#     category: archive-taxonomy
#     tag: archive-taxonomy
#   permalinks:
#     category: /:name/
#     tag: /:name/
# End Cấu hình jekyll-archives


# Cấu hình gốc
category_archive:
  type: liquid
  path: /categories/
tag_archive:
  type: liquid
  path: /tags/

analytics:
  provider: "google-gtag"
  google:
    tracking_id: "G-S05S9PCKB2" # Luồn dữ liệu sofsog.com
    anonymize_ip: true # default false


# _config.yml (defaults)
repository  : "thanhag/thanhag.github.io" # Git username/repo-name e.g. "mmistakes/minimal-mistakes"
comments:
  provider  : "staticman_v2"
  staticman:
    branch    : "master"
    endpoint  : https://staticman.sofsog.com/v2/entry/

#     # http://95.179.130.240/v3/connect/thanhag/thanhag.github.io
#     # https://staticman.sofsog.com/v3/connect/thanhag/thanhag.github.io

#     # https://staticman-weathered-sea-2594.fly.dev/v3/connect/thanhag/thanhag.github.io


# comments:
#   provider: "utterances"
#   utterances:
#     theme: "github-light" # "github-dark"
#     issue_term: "pathname"
#     label: "comment" # Optional - must be existing label.

# comments:
#   provider: "facebook"
#   facebook:
#     appid: 949385505167728 # optional
#     num_posts: 5 # 5 (default)
#     colorscheme: "light" # "light" (default), "dark"


